on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: copilot
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Show current working directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files:"
          ls -la

      - name: Docker pull ARM MCP image
        run: docker pull armswdev/arm-mcp:latest
        timeout-minutes: 20
